name: Android CI

on:
  pull_request:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e


      - name: Run unit tests
        run: ./gradlew testDebugUnitTest


      - name: Generate Kover report
        run: ./gradlew koverXmlReport


      - name: Coverage check (80% gate)
        run: ./gradlew coverageCheck


      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2
        with:
          files: app/build/reports/kover/xml/report.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true


      - name: SonarQube Scan
        run: ./gradlew sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_SCANNER_OPTS: "-Dsonar.token=${{ secrets.SONAR_TOKEN }}"